---      
- name: installing the httpd and add firewalld
  hosts: webservers
  become: yes
  tasks: 

      - name: installing the httpd
        ansible.builtin.dnf:                                                                                                 
          name:
             - httpd
             - firewalld
          state: latest
      
      - name: Start service httpd, if not started
        ansible.builtin.service:
          name: "{{ item }}"
          state: started
          enabled: yes
        loop:
          - httpd
          - firewalld
      
      - name: adding http service through firewall-cmd
        ansible.posix.firewalld:
          service: http
          permanent: true
          state: enabled
          immediate: true

      - name: create index.html file
        ansible.builtin.copy:
          dest: /var/www/html/index.html
          content:  "Server name is: {{ ansible_hostname }}"
